### PR TITLE
[#issue-439] Fix the issue of long debug info in http response body.

### PR DESCRIPTION
**Pull request by ada2468**
[#issue-439] Fix the issue of long debug info in http response body.

Cause of issue:

```python3
# at src/dashboard/src/utils/request.js
Line 48: err(e), status=status.HTTP_409_CONFLICT

```
err(e) contains all the debug information, and should be replaced with a better error message.

Solution:
replace object e with better error messages like 'Email Aleady exists!'.

Additional Features:
I implemented notifications for login and register error message in dashboard.

Signed-off-by: ada2468 jx2161@nyu.edu

### CODE REVIEW

**Review by ada2468 — COMMENTED** [review]
Signed-off-by: ada2468 [jx2161@nyu.edu](mailto:jx2161@nyu.edu)

**Comment by yeasy** [comment]
@fengyangsy please help review.

**Comment by yeasy** [comment]
Do not know why it always complains about the DCO with a given sign-off in the commit msg.

@ryanjjones10 Would you like to help have a look on the CI service?

Thanks!

**Pull request closed without merging**
