### PR TITLE
improvement: upgrade umi version to 3.0

### LINKED ISSUE #152: upgrade umi version to 3.0
upgrade umi verson to 3.0

### PR DESCRIPTION
**Pull request by hightall**
fix #152

Signed-off-by: Haitao Yue <hihghtallyht@gmail.com>

### CODE REVIEW

**Comment by litong01** [comment]
@hightall you got 2 commits in this PR. Can you squash them into one?

**Comment by litong01** [comment]
A lot of checks also failed on the second commit.

**Comment by yeasy** [comment]
This is an important change, let's review carefully to avoid breaking existing functionalities.
@hightall @litong01 @jiahaoc1993

**Comment by hightall** [comment]
@litong01 it's netlify build, I have removed it, it's just a demo site deployment.

**Pull request merged**
