### PR TITLE
Upgrade chaincode installation to Fabric V2.5.10

### PR DESCRIPTION
**Pull request by YoungHypo**

### CODE REVIEW

**Review by xichen1 — COMMENTED** [review]
The PR looks good overall. From what I see, it is primarily code refactoring and cleanup. Just to confirm, does the chaincode installation remain unchanged during the version upgrade?

**Comment by YoungHypo** [comment]
Yes, the underlying CLI is still the same as in the previous version 2.2.0

**Comment by YoungHypo** [comment]
> The PR looks good overall. From what I see, it is primarily code refactoring and cleanup. Just to confirm, does the chaincode installation remain unchanged during the version upgrade?

Thank you. Yes, the underlying CLI is still the same as in the previous version 2.2.0

**Review by xichen1 — APPROVED** [review]
LGTM!

**Pull request merged**
